#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     bottom_limit,   sensorTouch)
#pragma config(Sensor, S3,     top_limit,      sensorTouch)
#pragma config(Motor,  mtr_S1_C1_1,     motor_left,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     motor_right,   tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     arm_extension_motor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     arm_tilt_motor, tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C3_1,    ramp_servo,           tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "Drive Module.c"
#include "Arm Tilt.c"
#include "Arm Extension.c"
#include "Ramp Buttons.c"

task main()
{



	while(true)
	{
		getJoystickSettings(joystick);


		Driver();
		arm_tilt();
		arm_extension();
		ramp();

	}





}
